---

- name: INSTALL PACKAGES
  hosts: all

  vars_files:
    - ants.yml

  vars:
    - apt_list: "{{ ants | json_query(
                    'package_groups[].packages[?installed_by==`apt`][].name')
                 }}"
    - pip3_list: "{{ ants | json_query(
                    'package_groups[].packages[?installed_by==`pip3`][].name')
                 }}"

  tasks:

    - debug:
        msg: "installing via apt: {{ apt_list }}"

    - name: install packages via apt
      become: true
      apt:
        name: "{{ apt_list }}"
        state: latest
        update_cache: true
        cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"

    - debug:
        msg: "installing via pip3: {{ pip3_list }}"

    - name: install python3 packages via pip3
      pip:
        name: "{{ pip3_list }}"
        extra_args: --user
        executable: pip3


- name: SYSTEM TWEAKS
  hosts: all

  tasks:

    - name: suppress ubuntu motd & lastlogin
      become: true
      shell: |
        chmod a-x /etc/update-motd.d/*
        echo "PrintLastLog no" >> /etc/ssh/sshd_config
        systemctl reload ssh.service
      args:
        warn: false

    - name: set hostname
      become: true
      hostname:
        name: ants

    - name: copy various files for root and vagrant
      become: true
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        backup: true
      loop:
        - {src: 'files/motd', dest: '/etc/motd',
           owner: root, group: root, mode: 644}
        - {src: 'files/bash.sh', dest: '/root/.bash.sh',
           owner: root, group: root, mode: 644}
        - {src: 'files/dir_colors', dest: '/root/.dir_colors',
           owner: root, group: root, mode: 644}
        - {src: 'files/vim/vimrc', dest: '/root/.vimrc',
           owner: root, group: root, mode: 644}
        - {src: 'files/vim/', dest: '/root/.vim',
           owner: root, group: root, mode: preserve}

        - {src: 'files/bash.sh', dest: '/home/vagrant/.bash.sh',
           owner: vagrant, group: vagrant, mode: 644}
        - {src: 'files/dir_colors', dest: '/home/vagrant/.dir_colors',
           owner: vagrant, group: vagrant, mode: 644}
        - {src: 'files/vim/vimrc', dest: '/home/vagrant/.vimrc',
           owner: vagrant, group: vagrant, mode: 644}
        - {src: 'files/vim/', dest: '/home/vagrant/.vim',
           owner: vagrant, group: vagrant, mode: preserve}

    - name: bashrc for user - vagrant
      lineinfile:
        path: /home/vagrant/.bashrc
        insertafter: EOF
        line: source /home/vagrant/.bash.sh

    - name: bashrc for user - root
      become: true
      lineinfile:
        path: /root/.bashrc
        insertafter: EOF
        line: source /root/.bash.sh
