# -*- mode: ruby -*-
# vi: set ft=ruby :
# https://docs.vagrantup.com

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5000, host: 5000, host_ip: "127.0.0.1"

  # private management network for devices to connect to (assign .1 to host machine)
  config.vm.network 'private_network', ip: "10.250.0.11", netmask: 24, name: "vboxnet0"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"

    # disables console output logging to file
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  # User is "root".
  config.vm.provision "shell", inline: <<-SHELL
    # Ensure latest Ansible via APT
    apt-get update # && apt-get dist-upgrade --yes
    apt-get install --yes software-properties-common apt-transport-https

    # Python3 + PIP3
    apt-get install python3-pip --no-install-recommends --yes

    # Python2 + PIP2
    apt-get install python-minimal python-pip python-virtualenv python-setuptools --no-install-recommends --yes
  SHELL

  # User is "vagrant".
  # These MUST be done in a separate shell as they change the pip path.
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    # Python3 + PIP3 + ansible
    pip3 install -U --user pip setuptools

    # Python2 + PIP2
    pip2 install -U --user pip setuptools
  SHELL

  # User is "vagrant".
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    # Python3 + ansible
    pip3 install -U --user "ansible>=2.7,<2.8" jmespath
  SHELL

  # User is "vagrant". Runs ansible inside of the VM on itself.
  config.vm.provision "ansible_local" do |ansible|
    ansible.install = false
    ansible.playbook = "provision-ants.yml"
  end

  # Installs latest docker-ce
  config.vm.provision "docker"

end




