set nocompatible
" Show the cursor position
set ruler
set expandtab
" Make tabs as wide as two spaces
"set tabstop=2
" Show a marker at column 80
set colorcolumn=88,110
" Enable line numbers
set number
" Highlight current line
set cursorline
" Show “invisible” characters
set list
set showbreak=↪\
set listchars=tab:→\ ,nbsp:␣,trail:·,extends:⟩,precedes:⟨
" Highlight searches
set hlsearch
" Ignore case of searches
set ignorecase
" ... but not when search pattern contains upper case characters
set smartcase
" Highlight dynamically as pattern is typed
set incsearch
" Disable error bells
set noerrorbells
" Don’t reset cursor to start of line when moving around.
set nostartofline
" Show the current mode
set showmode
" Start scrolling three lines before the horizontal window border
set scrolloff=3

" Allow color schemes to do bright colors without forcing bold.
if &t_Co == 8 && $TERM !~# '^linux\|^Eterm'
  set t_Co=16
endif

" store swap, backup and undo files in /tmp with unique filenames
set backupdir=/tmp//
set directory=/tmp//
set undodir=/tmp//

" Do not show stupid q: window
map q: :q
" trim all whitespaces away
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

" KEY REMAPS
" trim all whitespaces away
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>
" tab navigation
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>

" COLORS
syntax enable
filetype off
filetype plugin indent on

set termguicolors     " enable true colors support
let ayucolor="dark"   " dark/light/mirage
colorscheme ayu

highlight TabLineFill cterm=none
highlight TabLine cterm=none ctermfg=darkgrey ctermbg=none

"let g:indentLine_enabled = 0
" UTF8 required!
let g:indentLine_char = '▏'

" FILETYPE PREFERENCES
autocmd FileType go setlocal noet ts=4 sw=4
autocmd FileType sh setlocal noet ts=4 sw=4
autocmd BufRead,BufNewFile *.js setlocal et ts=2 sw=2
autocmd FileType html setlocal et ts=2 sw=2
autocmd FileType scss setlocal et ts=2 sw=2
autocmd FileType yaml setlocal et ts=2 sw=2
autocmd FileType markdown setlocal tw=80 et ts=2 sw=2
autocmd FileType text setlocal tw=80
autocmd FileType python setlocal et ts=4 sw=4


" SIMPLE STATUS LINE
set laststatus=2
set statusline=[%n]
set statusline+=[%{mode()}]
set statusline+=[%t]    "tail of the filename
set statusline+=[%{strlen(&fenc)?&fenc:'none'}, "file encoding
set statusline+=%{&ff}] "file format
set statusline+=%h      "help file flag
set statusline+=%m      "modified flag
set statusline+=%r      "read only flag
set statusline+=%y      "filetype
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor column
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file
