set nocompatible
" Show the cursor position
set ruler
set expandtab
" Make tabs as wide as two spaces
set tabstop=2
" Enable line numbers
set number
" Highlight current line
set cursorline
" Show “invisible” characters
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_
set list
" Highlight searches
set hlsearch
" Ignore case of searches
set ignorecase
" ... but not when search pattern contains upper case characters
set smartcase
" Highlight dynamically as pattern is typed
set incsearch
" Disable error bells
set noerrorbells
" Don’t reset cursor to start of line when moving around.
set nostartofline
" Show the current mode
set showmode
" Start scrolling three lines before the horizontal window border
set scrolloff=3

" Do not show stupid q: window
map q: :q
" trim all whitespaces away
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>


" COLORS
syntax enable
filetype off
filetype plugin indent on

set termguicolors     " enable true colors support
let ayucolor="dark"   " dark/light/mirage
colorscheme ayu

" STATUS LINE
set laststatus=2
set statusline=%t       "tail of the filename
set statusline+=[%{strlen(&fenc)?&fenc:'none'}, "file encoding
set statusline+=%{&ff}] "file format
set statusline+=%h      "help file flag
set statusline+=%m      "modified flag
set statusline+=%r      "read only flag
set statusline+=%y      "filetype
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor column
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file
